[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

sourceSets {
  main {
    java {
      exclude 'assaultfish/AssaultFish.java'
    }
  }
}

dependencies {
  implementation "com.badlogicgames.gdx:gdx:$gdxVersion"
  implementation "com.squidpony:squidlib:$squidLibVersion"
  implementation "com.squidpony:squidlib-util:$squidLibUtilVersion"
  implementation "com.github.tommyettinger:regexodus:$regExodusVersion"
}
        